# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Employ the Kalman Filter and Smoother
#'
#' @param y Matrix of observations.
#' @param y_isna Matrix indicating which observations are missing.
#' @param a Initial values of the state vector.
#' @param P_inf Diffuse part of the variance - covariance matrix of the
#'   state vector.
#' @param P_star Stationary part of the variance - covariance matrix of the
#'   state vector.
#' @param Z Z system matrix of the State Space model.
#' @param T T system matrix of the State Space model.
#' @param R R system matrix of the State Space model.
#' @param Q Q system matrix of the State Space model.
#' @param diagnostics Boolean indicating whether diagnostics should be computed.
#'
#' @noRd
KalmanC <- function(y, y_isna, a, P_inf, P_star, Z, T, R, Q, diagnostics) {
    .Call(`_statespacer_KalmanC`, y, y_isna, a, P_inf, P_star, Z, T, R, Q, diagnostics)
}

#' Employ the Kalman Filter to calculate the loglikelihood
#'
#' @param y Matrix of observations.
#' @param y_isna Matrix indicating which observations are missing.
#' @param a Initial values of the state vector.
#' @param P_inf Diffuse part of the variance - covariance matrix of the
#'   state vector.
#' @param P_star Stationary part of the variance - covariance matrix of the
#'   state vector.
#' @param Z Z system matrix of the State Space model.
#' @param T T system matrix of the State Space model.
#' @param R R system matrix of the State Space model.
#' @param Q Q system matrix of the State Space model.
#'
#' @noRd
LogLikC <- function(y, y_isna, a, P_inf, P_star, Z, T, R, Q) {
    .Call(`_statespacer_LogLikC`, y, y_isna, a, P_inf, P_star, Z, T, R, Q)
}

